"""initial

Revision ID: 00593876ee2f
Revises: 
Create Date: 2026-02-07 23:45:12.920609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00593876ee2f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(parent_id IS NULL AND level = 1) OR (parent_id IS NOT NULL AND level > 1)', name='check_activity_root_level'),
    sa.CheckConstraint('level >= 1 AND level <= 3', name='check_activity_level'),
    sa.ForeignKeyConstraint(['parent_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'parent_id', name='uq_activity_name_parent')
    )
    op.create_index(op.f('ix_activities_name'), 'activities', ['name'], unique=False)
    op.create_index('ix_activities_parent_id', 'activities', ['parent_id'], unique=False)
    op.create_index('ix_activities_parent_level', 'activities', ['parent_id', 'level'], unique=False)
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name='check_latitude_range'),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name='check_longitude_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_buildings_lat_lng', 'buildings', ['latitude', 'longitude'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_organizations_building_id', 'organizations', ['building_id'], unique=False)
    op.create_index('ix_organizations_name', 'organizations', ['name'], unique=False)
    op.create_table('organization_activities',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'activity_id')
    )
    op.create_index('ix_org_activities_activity_id', 'organization_activities', ['activity_id'], unique=False)
    op.create_table('organization_phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number', name='uq_phone_number')
    )
    op.create_index('ix_org_phones_organization_id', 'organization_phones', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_org_phones_organization_id', table_name='organization_phones')
    op.drop_table('organization_phones')
    op.drop_index('ix_org_activities_activity_id', table_name='organization_activities')
    op.drop_table('organization_activities')
    op.drop_index('ix_organizations_name', table_name='organizations')
    op.drop_index('ix_organizations_building_id', table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('ix_buildings_lat_lng', table_name='buildings')
    op.drop_table('buildings')
    op.drop_index('ix_activities_parent_level', table_name='activities')
    op.drop_index('ix_activities_parent_id', table_name='activities')
    op.drop_index(op.f('ix_activities_name'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
